### ISSUE TITLE
Improve visibility of other installation methods instructions

### ISSUE THREAD

**Issue by eminence** [rust-lang/beta.rust-lang.org#462] opened 2018-11-30 02:16 UTC
# Content Feature Request
## Summary
The download/getting started page (https://beta.rust-lang.org/learn/get-started) detects that I'm on Windows, and gives me instructions for downloading rustup-init.exe, or it gives me instructions if i'm using Windows Subsystem for Linux.

But it's not clear how to download rust for Linux.  (I happen to know that the Linux instructions are in fact the same as the WSL instructions, but the web page doesn't make this clear).   

(The old web site suffered from this problem as well, but now seems like a good time to try to fix this issue).

## Motivation

It's common for a user to be sitting at a Windows machine (and with a Windows browser), but they are actually remotely connected a Linux terminal where they want to install some software.  

In the current website version, a user needs to click 'Learn More About Installation' under the 'Windows Subsystem for Linux' section, and then click on 'Learn More' under the 'Other installation methods' section, and then read the 'Other ways to install rustup' section.

Reducing the time and number of clicks a user needs to find install instructions for their platform will improve user experience.

## Proposal

Since the WSL instructions are the same for Linux (and macOS), I propose that the "Windows Subsystem for Linux" section be renamed to "Unix or Windows Subsystem for Linux", and the below text say something like "If you're a Windows Subsystem for Linux user, or are using Linux or macOS, run the following in your terminal"

## Drawbacks
It will add additional information to the page that may not be relevant to the user.

## Rationale and alternatives
Rationale:  reduce the time and number of clicks a user needs to find install instructions for their platform.

## Maintenance
There should be no additional maintenance work with this change.

## Unresolved Questions
None at this time

**Comment by ashleygwilliams** [comment] 2018-11-30 03:56
closing as duplicate of https://github.com/rust-lang/beta.rust-lang.org/issues/423

**Closed by ashleygwilliams** 2018-11-30 03:56 UTC
Labels: duplicate
