### ISSUE TITLE
RSS feed is missing [regression]

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/beta.rust-lang.org#576] opened 2018-12-06 19:12 UTC
# Technical Feature Request
## Summary
The new website lacks an RSS feed. My feedreader points at https://blog.rust-lang.org/feed.xml and that just comes back with 404 now.  I wondered why I hadn't seen the edition announcement, now I know!

## Motivation
RSS worked on the old site. This is an unexpected regression.

## Drawbacks
Maybe this can't be auto-generated? But why shouldn't it?

**Comment by tyranron** [comment] 2018-12-06 19:15
Same here.

**Comment by ashleygwilliams** [comment] 2018-12-06 19:20
this is a dupe of a previous issue and also filed on the incorrect repo. the issue is here: https://github.com/rust-lang/blog.rust-lang.org/issues/311

**Closed by ashleygwilliams** 2018-12-06 19:20 UTC
